# Version
haskey(ENV, "UNO_RELEASE") || error("The environment variable UNO_RELEASE is not defined.")
version = VersionNumber(ENV["UNO_RELEASE"])
version2 = ENV["UNO_RELEASE"]
package = "Uno"

platforms = [
   ("aarch64-apple-darwin-cxx11"  , "lib", "dylib"),
   ("aarch64-linux-gnu-cxx11"     , "lib", "so"   ),
#  ("aarch64-linux-musl-cxx11"    , "lib", "so"   ),
#  ("powerpc64le-linux-gnu-cxx11" , "lib", "so"   ),
   ("x86_64-apple-darwin-cxx11"   , "lib", "dylib"),
   ("x86_64-linux-gnu-cxx11"      , "lib", "so"   ),
#  ("x86_64-linux-musl-cxx11"     , "lib", "so"   ),
#  ("x86_64-unknown-freebsd-cxx11", "lib", "so"   ),
   ("x86_64-w64-mingw32-cxx11"    , "bin", "dll"  ),
]

for (platform, libdir, ext) in platforms

  tarball_name = "$package.v$version.$platform.tar.gz"

  if isfile("products/$(tarball_name)")
    # Unzip the tarball generated by BinaryBuilder.jl
    isdir("products/$platform") && rm("products/$platform", recursive=true)
    mkdir("products/$platform")
    run(`tar -xzf products/$(tarball_name) -C products/$platform`)

    if isfile("products/$platform/deps.tar.gz")
      # Unzip the tarball of the dependencies
      run(`tar -xzf products/$platform/deps.tar.gz -C products/$platform`)

      # Copy the license of each dependency
      for folder in readdir("products/$platform/deps/licenses")
       cp("products/$platform/deps/licenses/$folder", "products/$platform/share/licenses/$folder")
      end
      rm("products/$platform/deps/licenses", recursive=true)

      # Copy the shared library of each dependency
      for file in readdir("products/$platform/deps")
        cp("products/$platform/deps/$file", "products/$platform/$libdir/$file")
      end

      # Remove the folder used to unzip the tarball of the dependencies
      rm("products/$platform/deps", recursive=true)
      rm("products/$platform/deps.tar.gz", recursive=true)

      # Remove the headers that are not related to Uno
      rm("products/$platform/include/libseq", recursive=true)
      rm("products/$platform/include/hwloc", recursive=true)
      rm("products/$platform/include/highs", recursive=true)
      for file in readdir("products/$platform/include")
        if endswith(file, ".h")
          rm("products/$platform/include/$file")
        end
      end

      # Remove the binaries that are not related to Uno
      for file in readdir("products/$platform/bin")
        if !startswith(file, "uno_ampl") && !startswith(file, "libuno") && !endswith(file, ".dll")
          rm("products/$platform/bin/$file")
        end
      end

      # Remove the libraries that are not dependencies of Uno
      rm("products/$platform/lib/pkgconfig", recursive=true)
      rm("products/$platform/lib/cmake", recursive=true)
      isfile("products/$platform/$libdir/libhsl_subset.$ext") && rm("products/$platform/$libdir/libhsl_subset.$ext")
      isfile("products/$platform/$libdir/libhsl_subset_64.$ext") && rm("products/$platform/$libdir/libhsl_subset_64.$ext")
      isfile("products/$platform/lib/libbqpd_dense.a") && rm("products/$platform/lib/libbqpd_dense.a")
      isfile("products/$platform/lib/libcharset.a") && rm("products/$platform/lib/libcharset.a")
      isfile("products/$platform/lib/libz.a") && rm("products/$platform/lib/libz.a")
      isfile("products/$platform/lib/libiconv.a") && rm("products/$platform/lib/libiconv.a")
      isfile("products/$platform/lib/libspral.dll.a") && rm("products/$platform/lib/libspral.dll.a")
      isfile("products/$platform/lib/libhwloc.dll.a") && rm("products/$platform/lib/libhwloc.dll.a")
      isfile("products/$platform/lib/libhighs.dll.a") && rm("products/$platform/lib/libhighs.dll.a")
      isfile("products/$platform/lib/libhwloc.def") && rm("products/$platform/lib/libhwloc.def")
      for file in readdir("products/$platform/$libdir")
        if startswith(file, "libasan") || startswith(file, "libubsan") || startswith(file, "libtsan") || startswith(file, "libhwasan") || startswith(file, "liblsan")
          rm("products/$platform/$libdir/$file")
        end
      end

      # Create a folder with only the libraries of the dependencies
      mkdir("products/$platform/deps")
      for file in readdir("products/$platform/$libdir")
        if !startswith(file, "uno_ampl") && !startswith(file, "libuno")
          mv("products/$platform/$libdir/$file", "products/$platform/deps/$file")
        end
      end
      isfile("products/$platform/lib/libbqpd.a") && mv("products/$platform/lib/libbqpd.a", "products/$platform/deps/libbqpd.a")

      # Create the archives *_binaries
      isfile("$(package)_binaries.$version2.$platform.tar.gz") && rm("$(package)_binaries.$version2.$platform.tar.gz")
      isfile("$(package)_binaries.$version2.$platform.zip") && rm("$(package)_binaries.$version2.$platform.zip")
      cd("products/$platform")

      # Create a folder with the version number of the package
      mkdir("$(package)_binaries.$version2")
      for folder in ("lib", "bin", "share", "include", "deps")
        cp(folder, "$(package)_binaries.$version2/$folder")
      end

      cd("$(package)_binaries.$version2")
      if ext == "dll"
        run(`zip -r --symlinks ../../../$(package)_binaries.$version2.$platform.zip lib bin share include deps`)
      else
        run(`tar -czf ../../../$(package)_binaries.$version2.$platform.tar.gz lib bin share include deps`)
      end
      cd("../../..")

      # Remove the folder used to unzip the tarball generated by BinaryBuilder.jl
      rm("products/$platform", recursive=true)
    else
      @warn("The tarball deps.tar.gz is missing in $(tarball_name)!")
    end
  # else
  #   @warn("The tarball for the platform $platform was not generated!")
  end
end
