site_name: Uno
theme:
  name: material
nav:
  - Introduction: 'index.md'
  - 'Getting started':
    - 'Uno options': 'options.md'
  - 'Unfiying nonlinear optimization':
    - 'Unification framework': 'unification_framework.md'
    - 'Uno solver': 'uno_solver.md'
  - 'Issue tracker': 'https://github.com/cvanaret/Uno/issues'
  - 'Checklists for developers': 'developers/checklists.md'
  - Acknowledgments: 'acknowledgments.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js