name = "UnoSolver"
uuid = "1baa60ac-02f7-4b39-a7a8-2f4f58486b05"
authors = ["Alexis Montoison <amontoison@anl.gov>", "Charlie Vanaret <vanaret@zib.de>"]
version = "0.2.10"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
Uno_jll = "396d5378-14f1-5ab1-981d-48acd51740ed"

[weakdeps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"

[extensions]
UnoSolverMathOptInterfaceExt = "MathOptInterface"
UnoSolverNLPModelsExt = "NLPModels"

[compat]
LinearAlgebra = "1.10"
MathOptInterface = "1.48"
NLPModels = "0.21.10"
OpenBLAS32_jll = "0.3.24"
SolverCore = "0.3.10"
Test = "1.10"
Uno_jll = "=2.7.0"
julia = "1.10"

[extras]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CUTEst", "HSL_jll", "MathOptInterface", "NLPModels", "Test"]
