name = "Uno"
uuid = "1baa60ac-02f7-4b39-a7a8-2f4f58486b05"
authors = ["Alexis Montoison <amontoison@anl.gov>", "Charlie Vanaret <vanaret@zib.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
Uno_jll = "396d5378-14f1-5ab1-981d-48acd51740ed"

[compat]
LinearAlgebra = "1.10"
OpenBLAS32_jll = "0.3.24"
Uno_jll = "2.0.1"
julia = "1.10"
