[general]
use_julia_native_enum_type = true
print_using_CEnum = false
library_name = "libuno"
output_file_path = "../src/libuno.jl"

[codegen]
use_julia_bool = true
use_ccall_macro = true
always_NUL_terminated_string = true

