name: ASAN and UBSAN on the C and Fortran examples

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'

env:
  BUILD_TYPE: Debug
  ASAN_OPTIONS: detect_leaks=1:abort_on_error=1
  UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gfortran cmake

      - name: Download dependencies
        shell: bash
        run: bash dependencies/scripts/download_dependencies.sh

      - name: Configure Uno CMake
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
            -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
            -DCMAKE_Fortran_FLAGS="-fcheck=all" \
            -DBQPD=${{github.workspace}}/dependencies/lib/libbqpd.a \
            -DLAPACK_LIBRARIES=${{github.workspace}}/dependencies/lib/liblapack.a \
            -DBLAS_LIBRARIES="${{github.workspace}}/dependencies/lib/libblas.a;${{github.workspace}}/dependencies/lib/libcblas.a" \
            -DBUILD_STATIC_LIBS=OFF \
            -DBUILD_SHARED_LIBS=ON .

      - name: Build Uno
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

      - name: Install Uno
        run: sudo cmake --install ${{github.workspace}}/build

      - name: Configure example CMake
        working-directory: ${{github.workspace}}/interfaces/C/example
        shell: bash
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
            -DUNO=/usr/local/lib/libuno.so .

      - name: Build C example
        working-directory: ${{github.workspace}}/interfaces/C/example
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run C example
        working-directory: ${{github.workspace}}/interfaces/C/example/build
        run: ./example_hs015

      - name: Compile Fortran example
        working-directory: ${{github.workspace}}/interfaces/Fortran
        run: |
          gfortran -g -O1 -fcheck=all -fbacktrace \
            example_uno.f90 -o example_uno \
            /usr/local/lib/libuno.so \
            -Wl,-rpath,/usr/local/lib

      - name: Run Fortran example
        working-directory: ${{github.workspace}}/interfaces/Fortran
        run: ./example_uno
