name: Build on macOS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        architecture: [x64, arm64]
        compiler: [gcc]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download dependencies
      shell: bash
      run: bash dependencies/scripts/download_dependencies.sh

    - name: Install Fortran compiler
      uses: fortran-lang/setup-fortran@main
      with:
        compiler: 'gcc'
        version: '13'

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                                             -DMUMPS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
                                             -DMETIS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
                                             -DBQPD=${{github.workspace}}/dependencies/lib/libbqpd.a \
                                             -DMETIS_LIBRARY=${{github.workspace}}/dependencies/lib/libmetis.a \
                                             -DMUMPS_LIBRARY=${{github.workspace}}/dependencies/lib/libdmumps.a \
                                             -DMUMPS_COMMON_LIBRARY=${{github.workspace}}/dependencies/lib/libmumps_common.a \
                                             -DMUMPS_PORD_LIBRARY=${{github.workspace}}/dependencies/lib/libpord.a \
                                             -DMUMPS_MPISEQ_LIBRARY=${{github.workspace}}/dependencies/lib/libmpiseq.a \
                                             -DBLAS_LIBRARIES="${{github.workspace}}/dependencies/lib/libblas.a;${{github.workspace}}/dependencies/lib/libcblas.a" \
                                             -DLAPACK_LIBRARIES=${{github.workspace}}/dependencies/lib/liblapack.a \
                                             -DHIGHS=${{github.workspace}}/dependencies/lib/libhighs.a

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j4