name: Build with MSVC

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        architecture: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment to compile C++ with MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Fortran compiler
      uses: fortran-lang/setup-fortran@main
      with:
        compiler: 'intel'
        version: '2025.0'

    - name: Download dependencies
      shell: bash
      run: bash dependencies/scripts/download_dependencies.sh

    - name: Compile BLAS and LAPACK
      shell: cmd
      run: |
        rm ${{github.workspace}}\dependencies\lib\libblas.a
        rm ${{github.workspace}}\dependencies\lib\libcblas.a
        rm ${{github.workspace}}\dependencies\lib\liblapack.a
        git clone https://github.com/Reference-LAPACK/lapack.git
        cd lapack
        mkdir build
        cd build
        cmake -G "NMake Makefiles" .. ^
          -DCBLAS=ON ^
          -DLAPACKE=OFF ^
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}\dependencies ^
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ^
          -DCMAKE_C_COMPILER=cl ^
          -DCMAKE_CXX_COMPILER=cl ^
          -DCMAKE_Fortran_COMPILER=ifx ^
          -DBUILD_SHARED_LIBS=OFF ^
          -DBUILD_INDEX64_EXT_API=OFF ^
          -DTEST_FORTRAN_COMPILER=OFF
        nmake
        nmake install

    - name: Configure CMake
      shell: cmd
      run: |
        cmake -G "NMake Makefiles" ^
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ^
              -DCMAKE_C_COMPILER=cl ^
              -DCMAKE_CXX_COMPILER=cl ^
              -DCMAKE_Fortran_COMPILER=ifx ^
              -DMUMPS_INCLUDE_DIR=${{github.workspace}}\dependencies\include ^
              -DMETIS_INCLUDE_DIR=${{github.workspace}}\dependencies\include ^
              -DBQPD=${{github.workspace}}\dependencies\lib\libbqpd.a ^
              -DMETIS_LIBRARY=${{github.workspace}}\dependencies\lib\libmetis.a ^
              -DMUMPS_LIBRARY=${{github.workspace}}\dependencies\lib\libdmumps.a ^
              -DMUMPS_COMMON_LIBRARY=${{github.workspace}}\dependencies\lib\libmumps_common.a ^
              -DMUMPS_PORD_LIBRARY=${{github.workspace}}\dependencies\lib\libpord.a ^
              -DMUMPS_MPISEQ_LIBRARY=${{github.workspace}}\dependencies\lib\libmpiseq.a ^
              -DBLAS_LIBRARIES="${{github.workspace}}\dependencies\lib\libblas.lib;${{github.workspace}}\dependencies\lib\libcblas.lib" ^
              -DLAPACK_LIBRARIES=${{github.workspace}}\dependencies\lib\liblapack.lib ^
              -DHIGHS=${{github.workspace}}\dependencies\lib\libhighs.a ^
              -DBUILD_STATIC_LIBS=ON ^
              -DBUILD_SHARED_LIBS=OFF .

    - name: Build
      run: nmake