name: Test of the Python example on Linux

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x64]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.12"
          architecture: 'x64'
          
      - name: Install pybind11
        run: |
          sudo apt install -y python3-pybind11 pybind11-dev

      - name: Compile and install unopy
        run: pip install .

      - name: Run example
        working-directory: ${{github.workspace}}/bindings/python/example
        run: python example_hs015.py