name: Unit tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          # ---------- LINUX ----------
          - os: ubuntu-latest
            toolchain: gcc
            build_type: Debug
            shell: bash

          - os: ubuntu-24.04-arm
            toolchain: gcc
            build_type: Debug
            shell: bash

          # ---------- MACOS ----------
          - os: macos-latest
            toolchain: gcc
            build_type: Debug
            shell: bash

          - os: macos-15-intel
            toolchain: gcc
            build_type: Debug
            shell: bash

          # ---------- WINDOWS MINGW ----------
          - os: windows-latest
            toolchain: mingw
            build_type: Debug
            shell: msys2 {0}

    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - uses: actions/checkout@v4

      # =========================================================
      # TOOLCHAIN SETUP
      # =========================================================

      # ----- macOS -----
      - name: Install Fortran compiler (macOS)
        if: startsWith(matrix.os, 'macos')
        uses: fortran-lang/setup-fortran@main
        with:
          compiler: 'gcc'
          version: '14'

      - name: Install libomp (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libomp
          if [[ $(uname -m) == 'arm64' ]]; then
            echo "OPENMP_LIB=/opt/homebrew/opt/libomp/lib/libomp.dylib" >> $GITHUB_ENV
            echo "LIBGFORTRAN_FOLDER=/opt/homebrew/opt/gcc/lib/gcc/15" >> $GITHUB_ENV
          else
            echo "OPENMP_LIB=/usr/local/opt/libomp/lib/libomp.dylib" >> $GITHUB_ENV
            echo "LIBGFORTRAN_FOLDER=/usr/local/opt/gcc/lib/gcc/15" >> $GITHUB_ENV
          fi

      # ----- MinGW -----
      - name: Setup MSYS2
        if: matrix.toolchain == 'mingw'
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      # =========================================================
      # DEPENDENCIES
      # =========================================================

      - name: Download dependencies
        run: bash dependencies/scripts/download_dependencies.sh

      # =========================================================
      # CONFIGURE
      # =========================================================

      - name: Configure (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DENABLE_TESTS=ON \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_FORTRAN_COMPILER=gfortran \
            -DMUMPS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
            -DMETIS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
            -DBQPD=${{github.workspace}}/dependencies/lib/libbqpd.a \
            -DMETIS_LIBRARY=${{github.workspace}}/dependencies/lib/libmetis.a \
            -DMUMPS_LIBRARY=${{github.workspace}}/dependencies/lib/libdmumps.a \
            -DMUMPS_COMMON_LIBRARY=${{github.workspace}}/dependencies/lib/libmumps_common.a \
            -DMUMPS_PORD_LIBRARY=${{github.workspace}}/dependencies/lib/libpord.a \
            -DMUMPS_MPISEQ_LIBRARY=${{github.workspace}}/dependencies/lib/libmpiseq.a \
            -DBLAS_LIBRARIES="${{github.workspace}}/dependencies/lib/libcblas.a;${{github.workspace}}/dependencies/lib/libblas.a" \
            -DLAPACK_LIBRARIES=${{github.workspace}}/dependencies/lib/liblapack.a \
            -DHIGHS=${{github.workspace}}/dependencies/lib/libhighs.a \
            -DBUILD_STATIC_LIBS=ON \
            -DBUILD_SHARED_LIBS=OFF

      - name: Configure (Mac)
        if: startsWith(matrix.os, 'macos')
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DENABLE_TESTS=ON \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_Fortran_COMPILER=gfortran-15 \
            -DCMAKE_EXE_LINKER_FLAGS="-L${{env.LIBGFORTRAN_FOLDER}}" \
            -DCMAKE_SHARED_LINKER_FLAGS="-L${{env.LIBGFORTRAN_FOLDER}}" \
            -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp" \
            -DOpenMP_C_LIB_NAMES="omp" \
            -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp" \
            -DOpenMP_CXX_LIB_NAMES="omp" \
            -DOpenMP_omp_LIBRARY=${{ env.OPENMP_LIB }} \
            -DMUMPS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
            -DMETIS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
            -DBQPD=${{github.workspace}}/dependencies/lib/libbqpd.a \
            -DMETIS_LIBRARY=${{github.workspace}}/dependencies/lib/libmetis.a \
            -DMUMPS_LIBRARY=${{github.workspace}}/dependencies/lib/libdmumps.a \
            -DMUMPS_COMMON_LIBRARY=${{github.workspace}}/dependencies/lib/libmumps_common.a \
            -DMUMPS_PORD_LIBRARY=${{github.workspace}}/dependencies/lib/libpord.a \
            -DMUMPS_MPISEQ_LIBRARY=${{github.workspace}}/dependencies/lib/libmpiseq.a \
            -DBLAS_LIBRARIES="${{github.workspace}}/dependencies/lib/libcblas.a;${{github.workspace}}/dependencies/lib/libblas.a" \
            -DLAPACK_LIBRARIES=${{github.workspace}}/dependencies/lib/liblapack.a \
            -DHIGHS=${{github.workspace}}/dependencies/lib/libhighs.a \
            -DBUILD_STATIC_LIBS=ON \
            -DBUILD_SHARED_LIBS=OFF

      - name: Configure (MinGW)
        if: matrix.toolchain == 'mingw'
        shell: cmd
        run: |
          cmake -G "MinGW Makefiles" ^
            -B build ^
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ^
            -DENABLE_TESTS=ON ^
            -DMUMPS_INCLUDE_DIR=${{github.workspace}}\dependencies\include ^
            -DMETIS_INCLUDE_DIR=${{github.workspace}}\dependencies\include ^
            -DBQPD=${{github.workspace}}\dependencies\lib\libbqpd.a ^
            -DMETIS_LIBRARY=${{github.workspace}}\dependencies\bin\libmetis.dll ^
            -DMUMPS_LIBRARY=${{github.workspace}}\dependencies\lib\libdmumps.a ^
            -DMUMPS_COMMON_LIBRARY=${{github.workspace}}\dependencies\lib\libmumps_common.a ^
            -DMUMPS_PORD_LIBRARY=${{github.workspace}}\dependencies\lib\libpord.a ^
            -DMUMPS_MPISEQ_LIBRARY=${{github.workspace}}\dependencies\lib\libmpiseq.a ^
            -DBLAS_LIBRARIES="${{github.workspace}}\dependencies\lib\libcblas.a;${{github.workspace}}\dependencies\lib\libblas.a" ^
            -DLAPACK_LIBRARIES=${{github.workspace}}\dependencies\lib\liblapack.a ^
            -DHIGHS=${{github.workspace}}\dependencies\lib\libhighs.a ^
            -DAUXILIARY_LIBRARIES=${{github.workspace}}\dependencies\lib\libstdc++.a ^
            -DBUILD_STATIC_LIBS=OFF ^
            -DBUILD_SHARED_LIBS=ON

      # =========================================================
      # BUILD
      # =========================================================

      - name: Build
        run: cmake --build build --target run_unotest --config ${{env.BUILD_TYPE}}

      # =========================================================
      # TEST
      # =========================================================

      - name: Make DLLs visible (MinGW)
        if: matrix.toolchain == 'mingw'
        run: |
          echo "$(cygpath '${{github.workspace}}')/dependencies/bin" >> $GITHUB_PATH
          cp dependencies/bin/*.dll build/

      - name: Debug missing DLLs (MinGW)
        if: matrix.toolchain == 'mingw'
        working-directory: build
        run: |
          cygcheck ./run_unotest.exe || true

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}