name: Unit tests on MacOS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        architecture: [arm64]
        compiler: [clang]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                                             -DENABLE_TESTS=ON \
                                             -DBLAS_LIBRARIES=${{github.workspace}}/deps/lib/libblas.a \
                                             -DLAPACK_LIBRARIES=${{github.workspace}}/deps/lib/liblapack.a \
                                             -DBUILD_STATIC_LIBS=ON \
                                             -DBUILD_SHARED_LIBS=OFF .

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target run_unotest --config ${{env.BUILD_TYPE}} -j4

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute unit tests
      run: ./run_unotest