name: Unit tests on Linux

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v4
    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Download dependencies
      shell: bash
      run: bash dependencies/scripts/download_dependencies.sh

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                                             -DMUMPS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
                                             -DMETIS_INCLUDE_DIR=${{github.workspace}}/dependencies/include \
                                             -DBQPD=${{github.workspace}}/dependencies/lib/libbqpd.a \
                                             -DMETIS_LIBRARY=${{github.workspace}}/dependencies/lib/libmetis.a \
                                             -DMUMPS_LIBRARY=${{github.workspace}}/dependencies/lib/libdmumps.a \
                                             -DMUMPS_COMMON_LIBRARY=${{github.workspace}}/dependencies/lib/libmumps_common.a \
                                             -DMUMPS_PORD_LIBRARY=${{github.workspace}}/dependencies/lib/libpord.a \
                                             -DMUMPS_MPISEQ_LIBRARY=${{github.workspace}}/dependencies/lib/libmpiseq.a \
                                             -DBLAS_LIBRARIES="${{github.workspace}}/dependencies/lib/libblas.a;${{github.workspace}}/dependencies/lib/libcblas.a" \
                                             -DLAPACK_LIBRARIES=${{github.workspace}}/dependencies/lib/liblapack.a \
                                             -DHIGHS=${{github.workspace}}/dependencies/lib/libhighs.a \
                                             -DBUILD_STATIC_LIBS=ON \
                                             -DBUILD_SHARED_LIBS=OFF .

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target run_unotest --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute unit tests
      run: ./run_unotest
