name: Test unopy's set_logger_stream

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'

jobs:
  test_set_logger_stream:
    name: Test unopy's set_logger_stream
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download dependencies
        run: bash dependencies/scripts/download_dependencies.sh

      - name: Install Fortran compiler (macOS)
        if: startsWith(matrix.sys.os, 'macos')
        uses: fortran-lang/setup-fortran@main
        with:
          compiler: 'gcc'
          version: '13'

      - name: Set toolchain (macOS)
        if: startsWith(matrix.sys.os, 'macos')
        run: |
          cat > /tmp/clang_toolchain.cmake << 'EOF'
          set(CMAKE_C_COMPILER clang)
          set(CMAKE_CXX_COMPILER clang++)
          set(CMAKE_Fortran_COMPILER gfortran-15)
          set(OpenMP_C_FLAGS "-Xpreprocessor -fopenmp")
          set(OpenMP_CXX_FLAGS "-Xpreprocessor -fopenmp")
          set(OpenMP_C_LIB_NAMES omp)
          set(OpenMP_CXX_LIB_NAMES omp)
          set(OpenMP_omp_LIBRARY $OPENMP_LIB)
          set(CMAKE_EXE_LINKER_FLAGS "-L$LIBGFORTRAN_FOLDER -lgfortran -Wl,-rpath,$LIBGFORTRAN_FOLDER")
          set(CMAKE_SHARED_LINKER_FLAGS "-L$LIBGFORTRAN_FOLDER -lgfortran -Wl,-rpath,$LIBGFORTRAN_FOLDER")
          EOF

      - name: Set compilers (macOS)
        if: startsWith(matrix.sys.os, 'macos')
        run: |
          export CC=clang
          export CXX=clang++
          export FC=gfortran-15
          export CMAKE_TOOLCHAIN_FILE=/tmp/clang_toolchain.cmake

      - name: Install libomp (macOS)
        if: startsWith(matrix.sys.os, 'macos')
        run: |
          brew install libomp
          if [[ $(uname -m) == 'arm64' ]]; then
            echo "OPENMP_LIB=/opt/homebrew/opt/libomp/lib/libomp.dylib" >> $GITHUB_ENV
            echo "LIBGFORTRAN_FOLDER=/opt/homebrew/opt/gcc/lib/gcc/15" >> $GITHUB_ENV
          else
            echo "OPENMP_LIB=/usr/local/opt/libomp/lib/libomp.dylib" >> $GITHUB_ENV
            echo "LIBGFORTRAN_FOLDER=/usr/local/opt/gcc/lib/gcc/15" >> $GITHUB_ENV
          fi

      - name: Install unopy from sources
        run: pip install . -v

      - name: Run example
        working-directory: ${{github.workspace}}/.github/Python/
        run: python test_set_logger_stream.py