name: TestPyPI's unopy on Python example

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Active venv (Windows)
        if: runner.os == 'Windows'
        run: .venv\Scripts\activate
        
      - name: Active venv
        if: runner.os != 'Windows'
        run: source .venv/bin/activate

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel
      
      - name: Install unopy from TestPyPI
        run: pip install -v --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ unopy

      - name: Run example
        working-directory: ${{github.workspace}}/interfaces/Python/example
        run: python example_hs015.py
