name: unopy HSL/CoinHSL

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'

env:
  BUILD_TYPE: Debug
  VENV: /srv/lib/myenv
  LIBS: /srv/lib

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: gh-ar-cvanaret-uno-benchmark
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: bash dependencies/scripts/download_dependencies.sh

      - name: Compile and install unopy
        run: CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) ${{env.VENV}}/bin/pip install . -v -C cmake.define.UNO_PYBIND11_DETAILED_ERRORS=ON

  run-example:
    name: Example with ${{matrix.LIBHSL_NAME}}'s ${{matrix.HSL_SOLVER}}
    needs: build
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        LIBHSL: [libhsl/builddir/libhsl.so, coinhsl-2024.05.15/build/libcoinhsl.so]
        HSL_SOLVER: [MA57, MA27, MA86]
        include:
          - LIBHSL: libhsl/builddir/libhsl.so
            LIBHSL_NAME: libHSL
          - LIBHSL: coinhsl-2024.05.15/build/libcoinhsl.so
            LIBHSL_NAME: CoinHSL
        # this attaches a label to both paths
    steps:
      - uses: actions/checkout@v4

      - name: Configure example for ${{matrix.HSL_SOLVER}}
        working-directory: ${{github.workspace}}/interfaces/Python/example
        run: |
          # load the HSL library dynamically
          sed -i '/uno_solver.set_preset("ipopt")/a\\tuno_solver.set_option("libhsl_path", "${{env.LIBS}}/${{matrix.LIBHSL}}")' example_hs015.py
          # substitution of the linear solver
          sed -i 's/MUMPS/${{matrix.HSL_SOLVER}}/' example_hs015.py

      - name: Run example
        working-directory: ${{github.workspace}}/interfaces/Python/example
        env:
          PYTHONDONTWRITEBYTECODE: "1"
        run: |
          "${{env.VENV}}/bin/python" example_hs015.py
