name: unopy HSL

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
      - '*.yml'
      - '*.yaml'
      - 'docs/**'

env:
  BUILD_TYPE: Debug
  VENV: /home/optimi/cvanaret/myenv

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: bash dependencies/scripts/download_dependencies.sh

      - name: Compile and install unopy
        run: CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) ${{env.VENV}}/bin/pip install . -v

      - name: Run example
        working-directory: ${{github.workspace}}/interfaces/Python/example
        run: ${{env.VENV}}/bin/python example_hs015.py